services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: demo
      POSTGRES_USER: demo
      POSTGRES_DB: demo
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
